[package]
name = "app-libs"
version = "0.0.0"
edition = "2021"
authors = ["Tnze"]
license = "AGPL"

[dependencies]
ffxiv-crafting = { version = '7.0.3', features = ["serde-support"] }
serde = { version = "1.0", features = ["derive"] }
rand = "0.8.5"

[target.'cfg(not(target_family = "wasm"))'.dependencies]
num_cpus = "1.16.0"
