[package]
name = "app-libs"
version = "0.0.0"
edition = "2021"
authors = ["Tnze"]
license = "AGPL"

[dependencies]
ffxiv-crafting = { version = "6.3.3", features = ["serde-support"] }
serde = { version = "1.0", features = ["derive"] }
rand = "0.8.5"
