name: "publish"
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  publish-web:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: setup node
      uses: actions/setup-node@v1
      with:
        node-version: 16
    - name: install Rust nightly
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
    - name: install wasm-pack
      run:
        npm install -g wasm-pack
    - name: install app dependencies and build it
      run: yarn && yarn build-web
    # Run type check after the wasm package is built
    - name: run tsc
      run: yarn && yarn tsc --noEmit
    - name: upload files
      uses: actions/upload-artifact@v3
      with:
        name: bestcraft-dist
        path: dist/

  deploy-web:
    needs: publish-web
    runs-on: ubuntu-latest
    environment: FTP Deployer
    steps:
    - name: download files
      uses: actions/download-artifact@v3
      with:
        name: bestcraft-dist
    - name: sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ vars.FTP_SERVER }}
        username: ${{ vars.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: /

  publish-tauri:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-20.04, windows-latest]
    environment: UpdaterSigner
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v2
    - name: setup node
      uses: actions/setup-node@v1
      with:
        node-version: 16
    - name: install Rust nightly
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
    - name: install dependencies (ubuntu only)
      if: matrix.platform == 'ubuntu-20.04'
      run: |
        sudo apt-get update
        sudo apt-get install -y libgtk-3-dev webkit2gtk-4.0 libappindicator3-dev librsvg2-dev patchelf
    - name: install app dependencies and build it
      shell: bash
      run: yarn && yarn build
    - uses: tauri-apps/tauri-action@v0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
        TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
      with:
        tagName: v__VERSION__ # the action automatically replaces \_\_VERSION\_\_ with the app version
        releaseName: "BestCraft v__VERSION__"
        releaseBody: |
          v0.12.4
          - 添加了版权声明
          - 优化了背景颜色
        releaseDraft: false
        prerelease: false
