name: "publish"
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  publish-tauri:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-20.04, windows-latest]
    environment: UpdaterSigner
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v4
    - name: setup node
      uses: actions/setup-node@v3
      with:
        node-version: 20
    - run: corepack enable
    - name: install Rust nightly
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: nightly
    - name: install dependencies (ubuntu only)
      if: matrix.platform == 'ubuntu-20.04'
      run: |
        sudo apt-get update
        sudo apt-get install -y libgtk-3-dev webkit2gtk-4.0 libappindicator3-dev librsvg2-dev patchelf
    - name: install app dependencies and build it
      run: pnpm install
    - uses: tauri-apps/tauri-action@v0
      id: tauri_build
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
        TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
      with:
        tagName: v__VERSION__ # the action automatically replaces \_\_VERSION\_\_ with the app version
        releaseName: "BestCraft v__VERSION__"
        releaseBody: |
          v0.15.4
          - 修复亮色模式下“安定”球色看不清的问题
          - 添加7.0版本通知提示

          v0.15.5
          - 窗口宽度不足时自动折叠侧边菜单栏
          - 离开启动页新版本通知自动关闭

          v0.15.6
          - 修复切换配方后模拟器界面食药配装UI依然操作旧职业的问题
          - 修复分析器“计算装备属性适配范围”当属性刚好满足要求时计算不出结果的问题

        releaseDraft: false
        prerelease: false
